// Per-icon imports from Simple Icons (react-icons/si) keep the bundle small: only these glyphs ship.
// Tools without a glyph here (SHAP, Optuna, NLTK, Matplotlib, OpenAI, the Adobe apps, ...) fall back to a monogram.
import type { IconType } from 'react-icons';
import {
  SiPython,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiPytorch,
  SiMlflow,
  SiOnnx,
  SiTensorflow,
  SiHuggingface,
  SiSpacy,
  SiOpencv,
  SiPostgresql,
  SiMediapipe,
  SiFastapi,
  SiFlask,
  SiDjango,
  SiLaravel,
  SiSqlalchemy,
  SiSupabase,
  SiPydantic,
  SiMysql,
  SiDocker,
  SiGit,
  SiRailway,
  SiVercel,
  SiApachehadoop,
  SiApachehive,
  SiApachespark,
  SiApacheairflow,
  SiNextdotjs,
  SiReact,
  SiVite,
  SiTypescript,
  SiTailwindcss,
  SiChartdotjs,
  SiLeaflet,
  SiRadixui,
  SiFramer,
  SiStreamlit,
  SiFlutter,
  SiFigma,
  SiPlotly,
  SiMarkdown,
  SiClaude,
} from 'react-icons/si';

// icon slug (as written in skills-content.ts) -> component
export const ICONS: Record<string, IconType> = {
  python: SiPython,
  scikitlearn: SiScikitlearn,
  pandas: SiPandas,
  numpy: SiNumpy,
  pytorch: SiPytorch,
  mlflow: SiMlflow,
  onnx: SiOnnx,
  tensorflow: SiTensorflow,
  huggingface: SiHuggingface,
  spacy: SiSpacy,
  opencv: SiOpencv,
  postgresql: SiPostgresql,
  mediapipe: SiMediapipe,
  fastapi: SiFastapi,
  flask: SiFlask,
  django: SiDjango,
  laravel: SiLaravel,
  sqlalchemy: SiSqlalchemy,
  supabase: SiSupabase,
  pydantic: SiPydantic,
  mysql: SiMysql,
  docker: SiDocker,
  git: SiGit,
  railway: SiRailway,
  vercel: SiVercel,
  apachehadoop: SiApachehadoop,
  apachehive: SiApachehive,
  apachespark: SiApachespark,
  apacheairflow: SiApacheairflow,
  nextdotjs: SiNextdotjs,
  react: SiReact,
  vite: SiVite,
  typescript: SiTypescript,
  tailwindcss: SiTailwindcss,
  chartdotjs: SiChartdotjs,
  leaflet: SiLeaflet,
  radixui: SiRadixui,
  framer: SiFramer,
  streamlit: SiStreamlit,
  flutter: SiFlutter,
  figma: SiFigma,
  plotly: SiPlotly,
  markdown: SiMarkdown,
  claude: SiClaude,
};
